import { StyleSheet } from 'react-native'
import { COLORS } from '../../shared/theme/colors'

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8 },
  backButton: { width: 38, height: 38, borderRadius: 12, backgroundColor: COLORS.surface, justifyContent: 'center', alignItems: 'center' },
  topBarTitle: { fontSize: 18, fontWeight: '800', color: COLORS.text, flex: 1, textAlign: 'center', marginHorizontal: 12 },
  form: { paddingHorizontal: 16, paddingTop: 12 },
  toggleRow: { flexDirection: 'row', backgroundColor: COLORS.surface, borderRadius: 14, padding: 4, borderWidth: 1, borderColor: COLORS.border },
  toggleOption: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 10, borderRadius: 11, gap: 6 },
  toggleActive: { backgroundColor: COLORS.bg },
  toggleText: { fontSize: 14, fontWeight: '700', color: COLORS.textDim },
  toggleTextActive: { color: COLORS.accent },
  hintText: { fontSize: 12, color: COLORS.textDim, textAlign: 'center', marginTop: 10, marginBottom: 16 },
  eventToggle: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.surface, borderRadius: 14, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: COLORS.border },
  eventToggleActive: { borderColor: `${COLORS.accent}60` },
  eventIconCircle: { width: 40, height: 40, borderRadius: 12, backgroundColor: COLORS.bg, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  eventIconCircleActive: { backgroundColor: COLORS.accent },
  eventToggleContent: { flex: 1 },
  eventToggleTitle: { fontSize: 15, fontWeight: '700', color: COLORS.text },
  eventToggleTitleActive: { color: COLORS.accent },
  eventToggleDesc: { fontSize: 12, color: COLORS.textDim, marginTop: 2 },
  checkbox: { width: 24, height: 24, borderRadius: 8, borderWidth: 2, borderColor: COLORS.border, justifyContent: 'center', alignItems: 'center', marginLeft: 8 },
  checkboxActive: { backgroundColor: COLORS.accent, borderColor: COLORS.accent },
  eventFields: { backgroundColor: COLORS.surface, borderRadius: 14, marginBottom: 12, borderWidth: 1, borderColor: COLORS.border, overflow: 'hidden' },
  dateRow: { flexDirection: 'row', alignItems: 'center', padding: 14, borderBottomWidth: 1, borderBottomColor: COLORS.border, gap: 12 },
  dateInfo: { flex: 1 },
  dateLabel: { fontSize: 12, color: COLORS.textDim, fontWeight: '600' },
  dateValue: { fontSize: 15, color: COLORS.text, fontWeight: '700', marginTop: 2 },
  pickerContainer: { backgroundColor: COLORS.bg, borderBottomWidth: 1, borderBottomColor: COLORS.border, paddingVertical: 8 },
  pickerDone: { alignSelf: 'flex-end', paddingHorizontal: 16, paddingVertical: 8 },
  pickerDoneText: { color: COLORS.accent, fontSize: 15, fontWeight: '700' },
  locationRow: { flexDirection: 'row', alignItems: 'flex-start', paddingHorizontal: 14, gap: 12 },
  locationInput: { flex: 1, fontSize: 15, color: COLORS.text, paddingVertical: 14 },
  priceRow: { flexDirection: 'row', alignItems: 'center', padding: 14, gap: 12 },
  priceLabel: { fontSize: 12, color: COLORS.textDim, fontWeight: '600' },
  priceRight: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 8 },
  freeCheckbox: { width: 22, height: 22, borderRadius: 6, borderWidth: 2, borderColor: COLORS.border, justifyContent: 'center', alignItems: 'center' },
  freeCheckboxActive: { backgroundColor: COLORS.green, borderColor: COLORS.green },
  freeLabel: { fontSize: 14, fontWeight: '700', color: COLORS.textDim },
  freeLabelActive: { color: COLORS.green },
  priceInput: { backgroundColor: COLORS.bg, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, fontSize: 15, fontWeight: '700', color: COLORS.text, minWidth: 80, textAlign: 'right' },
  titleInput: { backgroundColor: COLORS.surface, borderRadius: 14, paddingHorizontal: 16, paddingVertical: 14, fontSize: 16, fontWeight: '700', color: COLORS.text, borderWidth: 1, borderColor: COLORS.border, marginBottom: 10 },
  contentInput: { backgroundColor: COLORS.surface, borderRadius: 14, paddingHorizontal: 16, paddingVertical: 14, fontSize: 15, color: COLORS.text, borderWidth: 1, borderColor: COLORS.border, minHeight: 120, marginBottom: 16 },
  errorText: { color: COLORS.error, fontSize: 13, fontWeight: '600', textAlign: 'center', marginBottom: 12 },
  createButton: { backgroundColor: COLORS.accent, borderRadius: 14, paddingVertical: 14, alignItems: 'center' },
  createButtonDisabled: { opacity: 0.5 },
  createButtonText: { fontSize: 16, fontWeight: '800', color: COLORS.white },
})

export default styles
