import { StyleSheet } from 'react-native'
import { COLORS } from './settingsShared'

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 100,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: COLORS.text,
    marginBottom: 24,
    letterSpacing: 0.5,
  },
  profileButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  profileButtonIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: COLORS.bg,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  profileButtonContent: {
    flex: 1,
  },
  profileButtonTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.text,
    marginBottom: 2,
  },
  profileButtonDesc: {
    fontSize: 12,
    color: COLORS.textDim,
  },
  createChorusButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  accessRequestButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  accessRequestPending: {
    borderColor: `${COLORS.gold}55`,
  },
  accessRequestApproved: {
    borderColor: `${COLORS.green}55`,
  },
  accessRequestIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: COLORS.bg,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  accessRequestContent: {
    flex: 1,
  },
  accessRequestTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.text,
    marginBottom: 2,
  },
  accessRequestDesc: {
    fontSize: 12,
    color: COLORS.textDim,
  },
  createChorusDisabled: {
    opacity: 0.6,
  },
  createChorusIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: COLORS.bg,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  createChorusContent: {
    flex: 1,
  },
  createChorusTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.text,
    marginBottom: 2,
  },
  createChorusDesc: {
    fontSize: 12,
    color: COLORS.textDim,
  },
  feedbackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginBottom: 12,
  },
  feedbackError: {
    backgroundColor: 'rgba(251, 146, 60, 0.1)',
  },
  feedbackSuccess: {
    backgroundColor: 'rgba(74, 222, 128, 0.1)',
  },
  feedbackText: {
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
  },
  section: {
    backgroundColor: COLORS.surface,
    borderRadius: 18,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 6,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.text,
    letterSpacing: 0.3,
  },
  sectionDesc: {
    fontSize: 13,
    color: COLORS.textDim,
    marginBottom: 16,
    marginLeft: 32,
  },
  optionRow: {
    gap: 10,
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.bg,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    gap: 12,
  },
  optionActive: {
    borderColor: COLORS.accent,
    backgroundColor: 'rgba(228, 90, 132, 0.08)',
  },
  flagText: {
    fontSize: 22,
  },
  optionText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textDim,
    flex: 1,
  },
  optionTextActive: {
    color: COLORS.text,
  },
  aboutText: {
    fontSize: 14,
    color: COLORS.textDim,
    lineHeight: 21,
    marginBottom: 16,
  },
  infoRows: {
    backgroundColor: COLORS.bg,
    borderRadius: 12,
    overflow: 'hidden',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  infoLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textDim,
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.text,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginHorizontal: 16,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.surface,
    paddingVertical: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: `${COLORS.accent}40`,
    marginTop: 8,
  },
  logoutText: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.accent,
    letterSpacing: 0.3,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalTouchBlocker: {
    width: '100%',
  },
  modalCard: {
    width: '100%',
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    padding: 24,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.text,
  },
  modalClose: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
    backgroundColor: COLORS.bg,
  },
  modalInput: {
    backgroundColor: COLORS.bg,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 12,
    paddingHorizontal: 14,
  },
  modalTextInput: {
    paddingVertical: 14,
    fontSize: 16,
    color: COLORS.text,
    fontWeight: '500',
  },
  multilineInput: {
    minHeight: 88,
    textAlignVertical: 'top',
  },
  modalHelperText: {
    fontSize: 13,
    lineHeight: 19,
    color: COLORS.textDim,
    marginBottom: 12,
  },
  profileLoadingWrap: {
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileInfoCard: {
    backgroundColor: COLORS.bg,
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: 16,
  },
  profileInfoRow: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 4,
  },
  profileInfoLabel: {
    fontSize: 13,
    color: COLORS.textDim,
    fontWeight: '600',
  },
  profileInfoValue: {
    fontSize: 15,
    color: COLORS.text,
    fontWeight: '700',
  },
  profileFieldLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 8,
  },
  profileHelperText: {
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.textDim,
    marginTop: -2,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    backgroundColor: COLORS.bg,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  cancelText: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.textDim,
  },
  createButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    backgroundColor: COLORS.accent,
  },
  createText: {
    fontSize: 15,
    fontWeight: '800',
    color: COLORS.white,
  },
  reviewModalCard: {
    maxHeight: '80%',
  },
  requestCard: {
    backgroundColor: COLORS.bg,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 14,
    marginBottom: 10,
  },
  requestHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    marginBottom: 6,
  },
  requestTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    color: COLORS.text,
  },
  requestStatus: {
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  requestPending: {
    color: COLORS.gold,
  },
  requestApproved: {
    color: COLORS.green,
  },
  requestRejected: {
    color: COLORS.error,
  },
  requestMeta: {
    fontSize: 12,
    color: COLORS.textDim,
    marginBottom: 4,
  },
  requestReason: {
    fontSize: 13,
    color: COLORS.text,
    lineHeight: 18,
    marginBottom: 8,
  },
  reviewActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  reviewRejectButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: 'rgba(251, 146, 60, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(251, 146, 60, 0.25)',
  },
  reviewRejectText: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.error,
  },
  reviewApproveButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: COLORS.accent,
  },
  reviewApproveText: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.white,
  },
  emptyReviewText: {
    fontSize: 14,
    color: COLORS.textDim,
    textAlign: 'center',
    paddingVertical: 18,
  },
})

export default styles
