import { StyleSheet } from 'react-native'
import { COLORS, TAP_BUTTON_SIZE } from './metronomeShared'

const styles = StyleSheet.create({
  container: { flex: 1, alignItems: 'center', backgroundColor: COLORS.bg, paddingTop: 12 },
  infoButton: { alignSelf: 'flex-end', marginRight: 16, width: 36, height: 36, justifyContent: 'center', alignItems: 'center', borderRadius: 18, backgroundColor: COLORS.surface },
  msDisplay: { width: '88%', paddingVertical: 20, paddingHorizontal: 16, marginTop: 12, borderRadius: 20, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center', justifyContent: 'center', minHeight: 100 },
  msPlaceholder: { fontSize: 16, color: COLORS.textDim, fontWeight: '500', fontStyle: 'italic' },
  msValue: { fontSize: 60, fontWeight: '900', letterSpacing: -2 },
  msUnit: { fontSize: 15, fontWeight: '700', color: COLORS.textDim, marginTop: -2, letterSpacing: 2, textTransform: 'uppercase' },
  bpmContainer: { flexDirection: 'row', alignItems: 'baseline', marginTop: 8, backgroundColor: COLORS.bg, paddingHorizontal: 14, paddingVertical: 5, borderRadius: 12 },
  bpmValue: { fontSize: 22, fontWeight: '800', color: COLORS.text, marginRight: 4 },
  bpmUnit: { fontSize: 11, fontWeight: '700', color: COLORS.textDim, letterSpacing: 1 },
  historyContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 14, gap: 8, height: 20 },
  historyDot: { width: 10, height: 10, borderRadius: 5 },
  scoreSection: { width: '88%', marginTop: 10, alignItems: 'center' },
  scoreRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%', marginBottom: 6 },
  scoreLabel: { fontSize: 15, fontWeight: '800', letterSpacing: 0.5 },
  scoreNumber: { fontSize: 14, fontWeight: '600', color: COLORS.textDim },
  scoreBarBg: { width: '100%', height: 5, borderRadius: 3, backgroundColor: COLORS.border, overflow: 'hidden' },
  scoreBarFill: { height: '100%', borderRadius: 3 },
  tapArea: { flex: 1, justifyContent: 'center', alignItems: 'center', width: '100%' },
  ripple: { position: 'absolute', width: TAP_BUTTON_SIZE, height: TAP_BUTTON_SIZE, borderRadius: TAP_BUTTON_SIZE / 2, borderWidth: 2 },
  tapButtonOuter: { width: TAP_BUTTON_SIZE, height: TAP_BUTTON_SIZE, borderRadius: TAP_BUTTON_SIZE / 2, shadowColor: COLORS.accent, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.4, shadowRadius: 20, elevation: 12 },
  tapButton: { width: '100%', height: '100%', borderRadius: TAP_BUTTON_SIZE / 2, backgroundColor: COLORS.accent, justifyContent: 'center', alignItems: 'center', overflow: 'hidden' },
  tapButtonInner: { alignItems: 'center', justifyContent: 'center' },
  tapText: { fontSize: 19, color: COLORS.white, fontWeight: '900', letterSpacing: 3, marginTop: 4 },
  resetContainer: { width: '88%', marginBottom: 90 },
  resetButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.surface, paddingVertical: 14, borderRadius: 14, borderWidth: 1, borderColor: COLORS.border },
  resetText: { fontSize: 16, color: COLORS.textDim, fontWeight: '700', letterSpacing: 0.5 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  modalTouchBlocker: { width: '100%' },
  modalCard: { width: '100%', backgroundColor: COLORS.surface, borderRadius: 20, padding: 24 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  modalTitle: { fontSize: 18, fontWeight: '800', color: COLORS.text, letterSpacing: 0.3 },
  modalClose: { width: 32, height: 32, justifyContent: 'center', alignItems: 'center', borderRadius: 16, backgroundColor: COLORS.bg },
  modalText: { fontSize: 14, fontWeight: '500', color: COLORS.textDim, lineHeight: 21, letterSpacing: 0.2, marginBottom: 20 },
  modalLegend: { gap: 10 },
  legendRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  legendDot: { width: 12, height: 12, borderRadius: 6 },
  legendText: { fontSize: 13, fontWeight: '600', color: COLORS.textDim },
})

export default styles
