import { StyleSheet } from 'react-native'
import { COLORS, PRACTICE_PAD_SIZE, TAP_BUTTON_SIZE } from './metronomeShared'

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  scrollContent: { paddingTop: 12, paddingBottom: 160, alignItems: 'center' },
  infoButton: { alignSelf: 'flex-end', marginRight: 16, width: 36, height: 36, justifyContent: 'center', alignItems: 'center', borderRadius: 18, backgroundColor: COLORS.surface },
  modeSwitch: { width: '88%', marginTop: 12, flexDirection: 'row', backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, borderRadius: 18, padding: 6, gap: 8 },
  modeButton: { flex: 1, borderRadius: 14, paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  modeButtonActive: { backgroundColor: COLORS.accent },
  modeButtonText: { color: COLORS.textDim, fontSize: 14, fontWeight: '800' },
  modeButtonTextActive: { color: COLORS.white },
  msDisplay: { width: '88%', paddingVertical: 20, paddingHorizontal: 16, marginTop: 14, borderRadius: 20, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center', justifyContent: 'center', minHeight: 100 },
  msPlaceholder: { fontSize: 16, color: COLORS.textDim, fontWeight: '500', fontStyle: 'italic' },
  msValue: { fontSize: 60, fontWeight: '900', letterSpacing: -2 },
  msUnit: { fontSize: 15, fontWeight: '700', color: COLORS.textDim, marginTop: -2, letterSpacing: 2, textTransform: 'uppercase' },
  bpmContainer: { flexDirection: 'row', alignItems: 'baseline', marginTop: 8, backgroundColor: COLORS.bg, paddingHorizontal: 14, paddingVertical: 5, borderRadius: 12 },
  bpmValue: { fontSize: 22, fontWeight: '800', color: COLORS.text, marginRight: 4 },
  bpmUnit: { fontSize: 11, fontWeight: '700', color: COLORS.textDim, letterSpacing: 1 },
  historyContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 14, gap: 8, height: 20 },
  historyDot: { width: 10, height: 10, borderRadius: 5 },
  scoreSection: { width: '88%', marginTop: 10, alignItems: 'center' },
  scoreRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%', marginBottom: 6 },
  scoreLabel: { fontSize: 15, fontWeight: '800', letterSpacing: 0.5 },
  scoreNumber: { fontSize: 14, fontWeight: '600', color: COLORS.textDim },
  scoreBarBg: { width: '100%', height: 5, borderRadius: 3, backgroundColor: COLORS.border, overflow: 'hidden' },
  scoreBarFill: { height: '100%', borderRadius: 3 },
  tapArea: { justifyContent: 'center', alignItems: 'center', width: '100%', minHeight: 280, marginTop: 8 },
  ripple: { position: 'absolute', width: TAP_BUTTON_SIZE, height: TAP_BUTTON_SIZE, borderRadius: TAP_BUTTON_SIZE / 2, borderWidth: 2 },
  tapButtonOuter: { width: TAP_BUTTON_SIZE, height: TAP_BUTTON_SIZE, borderRadius: TAP_BUTTON_SIZE / 2, shadowColor: COLORS.accent, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.4, shadowRadius: 20, elevation: 12 },
  tapButton: { width: '100%', height: '100%', borderRadius: TAP_BUTTON_SIZE / 2, backgroundColor: COLORS.accent, justifyContent: 'center', alignItems: 'center', overflow: 'hidden' },
  tapButtonInner: { alignItems: 'center', justifyContent: 'center' },
  tapText: { fontSize: 19, color: COLORS.white, fontWeight: '900', letterSpacing: 3, marginTop: 4 },
  sectionCard: { width: '88%', marginTop: 14, borderRadius: 20, padding: 16, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border },
  sectionLabel: { color: COLORS.textDim, fontSize: 13, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1 },
  rhythmMetaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12, marginTop: 8 },
  rhythmTitle: { flex: 1, color: COLORS.text, fontSize: 24, fontWeight: '900' },
  rhythmBadge: { backgroundColor: COLORS.bg, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 6 },
  rhythmBadgeText: { color: COLORS.textDim, fontSize: 13, fontWeight: '800' },
  rhythmSequenceSummary: { marginTop: 10, color: COLORS.textDim, fontSize: 15, lineHeight: 22 },
  rhythmSelectorContent: { paddingHorizontal: 16, gap: 10 },
  rhythmChip: { paddingHorizontal: 14, paddingVertical: 11, borderRadius: 14, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, minWidth: 108 },
  rhythmChipActive: { backgroundColor: COLORS.accent, borderColor: COLORS.accent },
  rhythmChipName: { color: COLORS.text, fontSize: 14, fontWeight: '800' },
  rhythmChipNameActive: { color: COLORS.white },
  rhythmChipTime: { color: COLORS.textDim, fontSize: 12, fontWeight: '700', marginTop: 3 },
  rhythmChipTimeActive: { color: 'rgba(255,255,255,0.8)' },
  beatSequenceWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 14 },
  beatChip: { borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: COLORS.bg, borderWidth: 1, borderColor: COLORS.border, minWidth: 78 },
  beatChipDone: { backgroundColor: 'rgba(73, 201, 126, 0.14)', borderColor: COLORS.green },
  beatChipCurrent: { backgroundColor: 'rgba(221, 173, 76, 0.18)', borderColor: COLORS.gold },
  beatChipLabel: { color: COLORS.text, fontSize: 14, fontWeight: '800' },
  beatChipMeta: { color: COLORS.textDim, fontSize: 11, fontWeight: '700', marginTop: 4 },
  nextBeatCard: { width: '88%', marginTop: 14, borderRadius: 20, paddingVertical: 18, paddingHorizontal: 18, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center' },
  nextBeatLabel: { color: COLORS.textDim, fontSize: 13, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1.1 },
  nextBeatValue: { color: COLORS.text, fontSize: 34, fontWeight: '900', marginTop: 8 },
  nextBeatHint: { color: COLORS.textDim, fontSize: 14, marginTop: 6, textAlign: 'center' },
  practiceStatsRow: { width: '88%', flexDirection: 'row', gap: 10, marginTop: 14 },
  practiceControlRow: { width: '88%', marginTop: 14 },
  practiceControlCard: { borderRadius: 18, paddingVertical: 16, paddingHorizontal: 14, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border },
  bpmAdjustRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 10 },
  bpmAdjustButton: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.bg, borderWidth: 1, borderColor: COLORS.border },
  bpmAdjustText: { color: COLORS.text, fontSize: 15, fontWeight: '800' },
  practiceStatCard: { flex: 1, borderRadius: 18, paddingVertical: 16, paddingHorizontal: 14, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border },
  practiceStatValue: { color: COLORS.text, fontSize: 26, fontWeight: '900' },
  practiceStatLabel: { color: COLORS.textDim, fontSize: 12, fontWeight: '700', marginTop: 4, textTransform: 'uppercase', letterSpacing: 0.9 },
  practiceFeedback: { width: '88%', marginTop: 14, borderRadius: 16, paddingVertical: 12, paddingHorizontal: 14, alignItems: 'center' },
  practiceFeedbackText: { fontSize: 15, fontWeight: '800' },
  pulseRow: { width: '88%', flexDirection: 'row', gap: 8, marginTop: 14, flexWrap: 'wrap' },
  pulseChip: { minWidth: 54, paddingHorizontal: 10, paddingVertical: 10, borderRadius: 12, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center' },
  pulseChipCurrent: { backgroundColor: 'rgba(73, 201, 126, 0.14)', borderColor: COLORS.green },
  pulseChipDone: { backgroundColor: 'rgba(221, 173, 76, 0.18)', borderColor: COLORS.gold },
  pulseChipMissed: { backgroundColor: 'rgba(219, 82, 77, 0.14)', borderColor: COLORS.error },
  pulseChipLabel: { color: COLORS.text, fontSize: 13, fontWeight: '900' },
  pulseChipMeta: { color: COLORS.textDim, fontSize: 10, fontWeight: '700', marginTop: 4 },
  practicePadsRow: { width: '88%', flexDirection: 'row', gap: 14, marginTop: 16 },
  practicePadOuter: { flex: 1, height: PRACTICE_PAD_SIZE, borderRadius: 26, shadowColor: COLORS.accent, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.25, shadowRadius: 16, elevation: 10 },
  practicePad: { flex: 1, borderRadius: 26, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 16, borderWidth: 2 },
  practicePadDum: { backgroundColor: '#9A473D', borderColor: '#B75B4F' },
  practicePadTek: { backgroundColor: '#315E8A', borderColor: '#417AB1' },
  practicePadCorrect: { borderColor: COLORS.green },
  practicePadWrong: { borderColor: COLORS.error },
  practicePadTitle: { color: COLORS.white, fontSize: 30, fontWeight: '900', letterSpacing: 0.5 },
  practicePadSubtitle: { color: 'rgba(255,255,255,0.8)', fontSize: 12, fontWeight: '700', marginTop: 8, textTransform: 'uppercase', letterSpacing: 1.1 },
  resetContainer: { width: '88%', marginTop: 20 },
  resetButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.surface, paddingVertical: 14, borderRadius: 14, borderWidth: 1, borderColor: COLORS.border },
  resetText: { fontSize: 16, color: COLORS.textDim, fontWeight: '700', letterSpacing: 0.5 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  modalTouchBlocker: { width: '100%' },
  modalCard: { width: '100%', backgroundColor: COLORS.surface, borderRadius: 20, padding: 24 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  modalTitle: { fontSize: 18, fontWeight: '800', color: COLORS.text, letterSpacing: 0.3 },
  modalClose: { width: 32, height: 32, justifyContent: 'center', alignItems: 'center', borderRadius: 16, backgroundColor: COLORS.bg },
  modalText: { fontSize: 14, fontWeight: '500', color: COLORS.textDim, lineHeight: 21, letterSpacing: 0.2, marginBottom: 20 },
  modalLegend: { gap: 10 },
  legendRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  legendDot: { width: 12, height: 12, borderRadius: 6 },
  legendText: { fontSize: 13, fontWeight: '600', color: COLORS.textDim },
})

export default styles
